import mongoose from 'mongoose';

const invoiceSchema = new mongoose.Schema(
  {
    invoiceNumber: { type: String, unique: true, index: true },
    project: { type: mongoose.SchemaTypes.ObjectId, ref: 'Project' },
    client: { type: mongoose.SchemaTypes.ObjectId, ref: 'Client', required: true },
    invoicePdf: { type: String },
    milestones: [{ type: String }],
    
    items: [{
      description: { type: String, required: true },
      quantity: { type: Number, default: 1 },
      unitPrice: { type: Number, required: true },
      amount: { type: Number, required: true }
    }],
    
    milestoneId: { type: mongoose.SchemaTypes.ObjectId, ref: 'Project.milestones' },
    
    totalAmount: { type: Number, required: true },
    subtotal: { type: Number },
    tax: { type: Number, default: 0 },
    gst: { type: Number, default: 0 },
    taxBreakdown: [{
      label: String,
      percentage: Number,
      amount: Number
    }],
    discount: { type: Number, default: 0 },
    currency: { type: String, default: 'USD' },
    
    isRecurring: { type: Boolean, default: false },
    autogenerated: { type: Boolean, default: false },
    subscriptionId: { type: String },
    
    status: {
      type: String,
      enum: ['draft', 'pending', 'partially_paid', 'paid', 'void', 'overdue', 'failed', 'refunded'],
      default: 'pending'
    },
    
    paymentHistory: [{
      amount: Number,
      method: String,
      transactionId: String,
      paidAt: { type: Date, default: Date.now }
    }],
    
    dueDate: { type: Date },
    paidAt: { type: Date },
    
    stripePaymentId: { type: String },
    stripeInvoiceUrl: { type: String },
    
    isDeleted: { type: Boolean, default: false }
  },
  {
    timestamps: true,
  }
);

invoiceSchema.pre('save', function(next) {
  if (!this.invoiceNumber) {
    this.invoiceNumber = 'INV-' + Math.random().toString(36).substring(2, 10).toUpperCase();
  }
  next();
});

const Invoice = mongoose.models.Invoice || mongoose.model('Invoice', invoiceSchema);

export default Invoice;
