import { StatusCodes } from 'http-status-codes';
import Project from '../models/Project.model.js';
import Invoice from '../models/Invoice.model.js';
import Client from '../models/Client.model.js';
import ActivityLog from '../models/ActivityLog.model.js';
import ApiError from '../utils/ApiError.js';
import { socketService } from './socket.service.js';

/**
 * Automated Milestone-to-Invoice Engine
 * Handles the financial lifecycle of project milestones.
 */
export const milestoneBillingService = {
  /**
   * Process a Milestone Status Change
   * Triggers automation rules based on state transitions.
   */
  handleMilestoneStatusChange: async (projectId, milestoneId, newStatus, actorId) => {
    const project = await Project.findById(projectId);
    if (!project) throw new ApiError(StatusCodes.NOT_FOUND, 'Project not found');

    const milestoneIndex = project.milestones.findIndex(m => m._id.toString() === milestoneId);
    if (milestoneIndex === -1) throw new ApiError(StatusCodes.NOT_FOUND, 'Milestone not found');

    const milestone = project.milestones[milestoneIndex];
    const oldStatus = milestone.status;

    // Update Status
    milestone.status = newStatus;
    if (newStatus === 'completed') milestone.completedAt = new Date();
    if (newStatus === 'approved') milestone.approvedAt = new Date();

    // RULE 1: Auto-generate invoice on Approval
    if (newStatus === 'approved' && !milestone.invoiceGenerated) {
      await milestoneBillingService.generateMilestoneInvoice(project, milestone, actorId);
    }

    await project.save();

    // Log Activity
    await ActivityLog.create({
      actorId,
      action: 'MILESTONE_STATUS_UPDATED',
      entityType: 'Project',
      entityId: projectId,
      clientId: project.client,
      details: { milestoneId, oldStatus, newStatus }
    });

    // Broadcast update
    socketService.to(`project_${projectId}`, 'MILESTONE_UPDATED', {
      milestoneId,
      status: newStatus
    });
  },

  /**
   * Enterprise Invoice Generation Logic
   */
  generateMilestoneInvoice: async (project, milestone, actorId) => {
    const subtotal = milestone.amount || 0;
    const gstRate = 0.18; // 18% standard GST
    const gst = subtotal * gstRate;
    const total = subtotal + gst;

    const invoice = await Invoice.create({
      project: project._id,
      client: project.client,
      milestoneId: milestone._id,
      autogenerated: true,
      items: [{
        description: `Milestone: ${milestone.title} - ${project.title}`,
        quantity: 1,
        unitPrice: subtotal,
        amount: subtotal
      }],
      subtotal,
      gst,
      taxBreakdown: [{
        label: 'GST',
        percentage: 18,
        amount: gst
      }],
      totalAmount: total,
      dueDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000), // 15 days net
      status: 'pending'
    });

    // Mark milestone as invoiced
    milestone.invoiceGenerated = true;
    milestone.invoiceId = invoice._id;
    milestone.status = 'invoiced';

    // Notify Client
    socketService.to(`client_${project.client}`, 'INVOICE_GENERATED', {
      invoiceId: invoice._id,
      invoiceNumber: invoice.invoiceNumber,
      amount: total
    });

    // Log for Finance Audit
    await ActivityLog.create({
      actorId,
      action: 'INVOICE_AUTOGENERATED',
      entityType: 'Invoice',
      entityId: invoice._id,
      clientId: project.client,
      details: { amount: total, milestoneId: milestone._id }
    });

    return invoice;
  }
};
